language:
- python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- nightly
install:
- python setup.py install
- pip install pylint coverage python-coveralls
script:
- export VER=$(python --version 2>&1 | awk '{print $2}' | awk 'BEGIN{FS="."}{printf("%d.%d",$1,$2)}')
- if [ "${VER}" == "2.7" -o "${VER}" == "3.3" -o "${VER}" == "3.4" ]; then pylint crabigator; fi
- nosetests --with-coverage
after_success:
- export VER=$(python --version 2>&1 | awk '{print $2}' | awk 'BEGIN{FS="."}{printf("%d.%d",$1,$2)}')
- if [ "${VER}" == "3.4" ]; then COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} coveralls; fi
env:
  global:
  - secure: JN7MYaPYsg4YUse+Q9xzaRRlRztsCU71CIm0yiXPnJW+zQAlJwWWTczZZgRZqzp91UmUXeVy7SDQIWUeTz2OrSMRXZ9crYsS6cbGQSp7jKcE2IGIeXpr88e+05o2Qn6xBS8wM+5hpsUfP3VPGDJBX3LArZd7k96h1dxJW2Ib9Z11bN1pMqzMwFiIaffjhJbENlT104H5zgScUNGFAr2Mr92/fpBc4y9dvKwEqX4gP6xwc1kjKsme2F8hCe8mzY3tBzX6XIlCJzueYrIBwArnCUKezZOAO5nMUVijqPRme7bUx8xd7L0HPZka9VP7Hr0HfuvkdIN5bkpIG+lifgep9qm3/ruVuLOZDmHipeEshfRfbdbESBuE9vhsAEByEZs4Qo8COo/xdGdnEIQRJpxrr34HgWyyA6nk+tkqv3bg9/8G4ZXRd9h+Vrv6AgA94xMUTPkN033UWzcnLNUs67nnICssFEPfEW2yuQ4WRLR+v7d2Q2Z3HCst3lUOSucTPOcIFQutxQkvaK/1Bhz/m9CuFNBifAgtFrK+dvUvvCj4xQxAYv8o2afcJKb4CY16B0dOjbqCOMibKjT1xo/ku/q4XLkgGRlXkUWb5OcES+K7OBOpQ6V51tkgySEEcrODy5X8NPK38IvuxFV/75Loxhx3Y5lCCDV9dhaBSLWxt7ftpgo=
  - secure: RNmZWUviVFkpMeHvAj3soDsr/FNO220n2hrhAxRQ90MZDFwxaq68/tCBVECIG0QuhHnXnNxUMoM2BC7jBD/QjknqGN7EuydCtmpe5V0LKT1BQu40x6JSo5L0C5f92XHw2WuWLCn4T2jRIalMCQhzLdLmJHvHWqe4dpYvXtIC26ZJb7lAVL9ZxBWjRXd2dVQxRS7A2FeF7s5qC+eL38xGS/+i5NChl5mYhORVIyMCl6fHtvuqo5wUyCn/6dcQptA1bxjcmP4Em0arzEfsSsJtj8cixyZvgDVOHmA+bsxNAwL0dLlVohq9mg2QLNojb+gykYgD0GoMZVgmZZz4yq/EnFMXKVTi0VuzmsU+0WEOXyIaIsZrNsORCq2jnDNtS5pWeyIFH4F7kyjGhbrxcEbKlgBkqKCQpsfTmUe2A6pY3kNLW4Gezq8de1+/QbMejQ44YK1tZpe39OtR/I8uzVygp9HsJA+sMTwX5iBFFzcQLFsz9qG6bupBgmI0WYJ9+k0dJwUGsUWdxQvKIkhk1eyTLKBUzq7birypdiOrp95k8NU6DlJlKe9/DKsDA/9QoXhs4IyBxDyqpOcazuLB7QVPZfbfwr7gfttAvqQA7/nfGbPn3BIsBDXgFDJ+eBWXm1unStIukegNAo3jHmm49gc38XQ9OCJyH/42546LesxB/6g=
